### ISSUE TITLE
Documentation for the project

### ISSUE THREAD

**Issue by vchrombie** [5-jigglypuff/pytrello2#6]
Update the `README.md` to include more sections
1. Installation
2. Getting Started
3. Authentication
4. Examples

Add Contribution Guidelines - `CONTRIBUTING.md`

**Comment by jessat** [comment]
Readme has been updated with additional sections.

**Comment by vchrombie** [comment]
> Readme has been updated with additional sections.

https://github.com/5-jigglypuff/pytrello2/commit/dbae52854e46e86539653253302ef54b5bfbfeb5
